apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: todo-service
build:
  local:
    push: false
    useBuildkit: true
  artifacts:
  - image: my_first_image
    docker:
      dockerfile: k8s/local.Dockerfile
    sync:
      manual:
        - src: 'dist/*.js'
          dest: '.'
        - src: 'dist/*.js.map'
          dest: '.'
        - src: 'dist/*.*'
          dest: '.'
deploy:
  helm:
    releases:
      - name: todo-service
        namespace: core
        chartPath: ./charts
        skipBuildDependencies: true
        setValueTemplates:
          image.repository: "{{.IMAGE_REPO_my_first_image}}"
          image.tag: "{{.IMAGE_TAG_my_first_image}}"
        setValues:
          image.pullPolicy: "IfNotPresent"
        valuesFiles:
          - ./ci/values/base/values.yaml
          - ./ci/values/overlay/local/values.yaml

