application:
  resources:
    requests:
      cpu: 200m
      memory: 200Mi
    limits:
      memory: 1000Mi
  env:
    JWT_ISSUER: "organization-service.production.your.rentals"
    EMAIL_VARS_ORGANIZATION_MANAGEMENT_PAGE: "app.your.rentals/organisation/management"
    ENABLE_FEATURE_FLAG_BY_DEFAULT: "true"
https://www:
  leapsome:
    com/app/#/auth/login:
externalSecrets:
  organization-service-database:
    secretStoreRef:
      name: core
    secretData:
      DB_CONNECTION_STRING: "{{ .DB_CONNECTION_STRING }}"
    remoteData:
      - secretKey: DB_CONNECTION_STRING
        remoteKey: "/yr-backend/production/app/organization-service/database/connection-string"
  organization-service-signing-keys:
    secretStoreRef:
      name: core
    secretData:
      secrets_0_kid: '{{ (index (fromJson .keys) 0).kid }}'
      secrets_0_private: '{{ (index (fromJson .keys) 0).private }}'
      secrets_0_public: '{{ (index (fromJson .keys) 0).public }}'
    remoteData:
      - secretKey: keys
        remoteKey: "/yr-backend/production/app/organization-service/authentication/signing-keys"
