name: Build and upload to ECR

on: [push]

jobs:
  build-and-upload-to-s3:
    runs-on: ubuntu-latest

    env:
      REGION: ap-southeast-1
      REPOSITORY_URL: 285574919501.dkr.ecr.ap-southeast-1.amazonaws.com
      REPOSITORY_NAME: vinhdo_backend
      APP_IMAGE_NAME: $REPOSITORY_URL/$REPOSITORY_NAME

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - run: npm ci
      - run: npm run build

      - name: Login ECR
        run: aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $REPOSITORY_URL

      - name: Create repository if not exist
        run: aws ecr describe-repositories --repository-names $REPOSITORY_NAME || aws ecr create-repository --repository-name $REPOSITORY_NAME

      - name: Set repository lifecycle policy
        run: aws ecr put-lifecycle-policy --repository-name $REPOSITORY_NAME --lifecycle-policy-text "file://ecr-policy.json"

      - name: Build image from bundle
        run: docker build -t $APP_IMAGE_NAME:$APP_IMAGE_TAG --build-arg BASE_IMAGE=public.ecr.aws/docker/library/node:16.15-alpine -f ./Dockerfile .

      - name: Push image to ECR
        run: docker push "${APP_IMAGE_NAME}:aaa"